### ISSUE TITLE
home page error

### ISSUE THREAD

**Issue by sgtram** [w32blaster/revizor#35]
NullPointerException occurred when processing request: [GET] /repository/dashboard/35
Stacktrace follows:
org.codehaus.groovy.grails.web.pages.exceptions.GroovyPagesException: Error processing GroovyPageView: Error executing tag <sc:buildFlatListofCommits>: null

**Comment by w32blaster** [comment]
# Todo:

* Remove folder while a repository deleting
* Show appropriate error message when cloning failed
